### ISSUE TITLE
I am studying the VDN algorithm and want to run your code. Can you list the environment it needs?

### ISSUE THREAD

**Issue by chuanshuo16nian** [ideal233/sf-vdn#2]

**Comment by chuanshuo16nian** [comment]
I am studying the VDN algorithm and want to run your code. Can you list the environment it needs?

**Comment by chuanshuo16nian** [comment]
What version of tensorflow should I use

**Comment by ideal233** [comment]
> 
> 
> What version of tensorflow should I use

Maybe you can try tf==1.4. There is no other special package that is needed. All packages needed can be installed by pip.

PS: This implementation of VDN is not very elegant...
